version: '3'



services:

  postgres-compose:

    image: postgres

    environment:

      POSTGRES_USERNAME: "postgres"

      POSTGRES_PASSWORD: "123456"

    ports:

      - "5432:5432"

    volumes:

      - C:/Users/doris.nunes/Documents/postgres:/var/lib/postgresql/data